### ISSUE TITLE
Release checklist for March 2021 update

### ISSUE THREAD

**Issue by MattJeanes** [MattJeanes/TARDIS#394]
Pending issues:
- [x] https://github.com/MattJeanes/TARDIS/issues/363
- [x] https://github.com/MattJeanes/TARDIS/issues/253
- [x] https://github.com/MattJeanes/TARDIS/issues/393

Go live process:
- [x] Testing completed
- [x] Raise pull request: #410 
- [x] Complete changelog
- [x] Legacy updated with Wiremod support, including change notes and a comment
- [x] Publish Old Default Extension: https://steamcommunity.com/sharedfiles/filedetails/?id=2425616806 
- [x] Doors updated
- [x] Rewrite updated
   - [x] New icon without Rewrite naming
   - [x] Edit title of addon to 'TARDIS' 
   - [x] Change photos to new default interior
   - [x] Edit description
     - [x] Edit about untextured static interior
     - [x] Add Artiom to credits
     - [x] Change credits of interior model from DiCHWer to Supermassive Games / BBC
   - [x] Add Artiom as an addon contributor
   - [x] Merge pull request
   - [x] Push update to workshop
   - [x] Remove TARDIS Legacy as a required item
   - [x] Change Notes
   - [x] Addon Updates
   - [x] Comment
- [ ] Extensions updated
- [ ] Close this issue

**Comment by parar020100** [comment]
Question: what happens to these copyrights now?
I suppose, interior and exterior models are now taken from legacy

![изображение](https://user-images.githubusercontent.com/32988384/111342810-db22d000-868b-11eb-8a72-629f3f411423.png)

**Comment by MattJeanes** [comment]
Yeah it'll just say Models because they're both from the same source now. DiCHWer's credit will be removed and moved onto the old default extension

**Comment by parar020100** [comment]
Don't forget to mention Brundoob as a contributor for the pointer model

**Comment by MattJeanes** [comment]
Release is ready for workshop deployment, scheduled for 2021-03-17T12:00Z

**Comment by MattJeanes** [comment]
Release complete
